# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicwalletapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to=settings.AUTH_USER_MODEL),
        ),
    ]
