# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwalletapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_musics',
            field=models.ManyToManyField(to='musicwalletapp.Music'),
        ),
    ]
